### ISSUE TITLE
node get_requests.js fails with "UnhandledPromiseRejectionWarning"

### ISSUE THREAD

**Issue by trivikr** [AllanFly120/cors-test#10]
```console
$ node -v
v14.15.0

$ node get_requests.js --v3dir ~/workspace/aws-sdk-js-v3 > output.md
(node:31107) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of undefined
    at getInputModel (/local/home/trivikr/workspace/cors-test/get_requests.js:62:9)
    at run (/local/home/trivikr/workspace/cors-test/get_requests.js:237:34)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:31107) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:31107) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

State in aws-sdk-js-v3 workspace: 
```
$ git log --pretty=format:"%H %an %ad" | head -5
e6b2ae1efab395cf645a8e280a4e21dd77b5ca12 AllanZhengYP Mon Nov 30 14:54:15 2020 -0800
6437e242f3848499f591f3d56f6f13e47be78a4f AllanZhengYP Mon Nov 30 13:49:22 2020 -0800
891eae20324271138bf745b9e0fce0e21aa2f07c Trivikram Kamat Tue Nov 24 09:37:37 2020 -0800
e9328760105ca6ce6a22002989d30a015c5b29fa Trivikram Kamat Tue Nov 24 09:37:10 2020 -0800
5fba8a4e40f3073239aa9b8f413e80bae1c1d491 AllanZhengYP Mon Nov 23 16:21:07 2020 -0800
```

**Comment by trivikr** [comment]
This issue happens as "amplifybackend" is not present in C2JModels

The service amplifybackend was added on 12/3/2020 https://github.com/aws/aws-sdk-js-v3/blob/master/codegen/sdk-codegen/aws-models/amplifybackend.2020-08-11.json

**Comment by AllanZhengYP** [comment]
I believe this issue can be fixed by upgrading the `aws-sdk` depency to the latest. The referred the service is available in v2: https://github.com/aws/aws-sdk-js/blob/master/apis/amplifybackend-2020-08-11.min.json
