### ISSUE TITLE
node get_requests.js fails with "UnhandledPromiseRejectionWarning"

### ISSUE THREAD

**Issue by trivikr** [AllanFly120/cors-test#12]
```console
$ node -v
v14.15.0

$ node get_requests.js --v3dir ~/workspace/aws-sdk-js-v3 > output.md
(node:31107) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of undefined
    at getInputModel (/local/home/trivikr/workspace/cors-test/get_requests.js:62:9)
    at run (/local/home/trivikr/workspace/cors-test/get_requests.js:237:34)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:31107) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:31107) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

State in aws-sdk-js-v3 workspace: 
```
$ git log --pretty=format:"%H %an %ad" | head -5
1f4b7cfbb801b139e52ca6814e344234599221d9 dependabot-preview[bot] Fri Dec 4 10:43:11 2020 -0800
58383dce968f01500b6c3ef07fead897787ed569 Trivikram Kamat Thu Dec 3 17:11:20 2020 -0800
113cc4d8b761023b02550ad0eba0398025a54f17 Trivikram Kamat Wed Dec 2 10:00:30 2020 -0800
4e02fbd946c286c1275664e6cc8f8e17defbb8a2 Trivikram Kamat Tue Dec 1 09:32:16 2020 -0800
11bc793940ea0373f7a8f01c2a622e6a6d9b1fcf Trivikram Kamat Tue Dec 1 09:31:58 2020 -0800
```

**Comment by trivikr** [comment]
Printed values in variables `endpointPrefix` and `commandName` before getInputModel call https://github.com/AllanZhengYP/cors-test/blob/35242d322f6dcc7950391bbbfa591ad492a3e73d/get_requests.js#L237

The values are:
```
connect
ListRealtimeContactAnalysisSegmentsCommand
```

This error is thrown as command `ListRealtimeContactAnalysisSegments` is in `connect-contact-lens` and not `connect`: https://github.com/aws/aws-sdk-js/blob/71d6fa9ad07f42e20eadbad11844301caae1a187/apis/connect-contact-lens-2020-08-21.min.json#L16

**Comment by trivikr** [comment]
This issue was fixed by updating endpoint provider in https://github.com/aws/aws-sdk-js-v3/pull/1824
