### ISSUE TITLE
get_requests.js fails with "Error: ValidationError: prefixed hostname must be hostname compatible." for gamma.11

### ISSUE THREAD

**Issue by trivikr** [AllanFly120/cors-test#5]
**Describe the bug**
get_requests.js fails with Error: ValidationError: prefixed hostname must be hostname compatible.

```console
$ node get_requests.js --v3dir ~/workspace/aws-sdk-js-v3 > output.md
(node:31602) UnhandledPromiseRejectionWarning: Error: ValidationError: prefixed hostname must be hostname compatible.
    at Object.exports.serializeAws_restXmlCreateAccessPointCommand (/local/home/trivikr/workspace/aws-sdk-js-v3/clients/client-s3-control/dist/cjs/protocols/Aws_restXml.js:47:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:31602) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:31602) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**To Reproduce**
Run command on commit https://github.com/aws/aws-sdk-js-v3/commit/cbdec4285e95b0bc01e0698c976c99e6156ad357

**Expected behavior**
Command succeeds without any error.

**Comment by trivikr** [comment]
The output when error is thrown:

<details>
<summary>Details</summary>

```console
<tr>
      <td><strong>s3.us-east-1.amazonaws.com</strong></td>
      <td>403 Forbidden</td>
      <td>❌</td>
      <td>❌ </td>
    </tr>
    <tr>
      <td colspan="4">
<details><summary>Details</summary>

<strong>cmd</strong>
<pre>
<code>
curl --insecure -i -X OPTIONS https://s3.us-east-1.amazonaws.com/stringValue/stringValue -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36" -H "Origin: https://foo.example" -H "Access-Control-Request-Method: DELETE" -H "Access-Control-Request-Headers: Content-Type,user-agent,host,Authorization,amz-sdk-invocation-id,amz-sdk-request,x-amz-security-token" -H "host: s3.us-east-1.amazonaws.com" 
</code>
</pre>

<strong>stdout</strong>
<pre>
<code>
  HTTP/1.1 403 Forbidden
  x-amz-request-id: CD41E5533750711F
  x-amz-id-2: X/guYT8amWKFqv+gjijKOYzAa4SkeLjIFo/NfpYvn+zzrfN3uNB41hVWND21SXPeHN30PKKL3LY=
  Content-Type: application/xml
  Transfer-Encoding: chunked
  Date: Thu, 15 Oct 2020 03:36:31 GMT
  Server: AmazonS3
  
  <?xml version="1.0" encoding="UTF-8"?>
  <Error><Code>AccessForbidden</Code><Message>CORSResponse: Bucket not found</Message><Method>DELETE</Method><ResourceType>BUCKET</ResourceType><RequestId>CD41E5533750711F</RequestId><HostId>X/guYT8amWKFqv+gjijKOYzAa4SkeLjIFo/NfpYvn+zzrfN3uNB41hVWND21SXPeHN30PKKL3LY=</HostId></Error>
</code>
</pre>


<strong>stderr</strong>
<pre>
<code>
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
  Dload  Upload   Total   Spent    Left  Speed
100   321    0   321    0     0   1154      0 --:--:-- --:--:-- --:--:--  1154

</code>
</pre>

</details>
      </td>
    </tr>
(node:27487) UnhandledPromiseRejectionWarning: Error: ValidationError: prefixed hostname must be hostname compatible.
    at Object.exports.serializeAws_restXmlCreateAccessPointCommand (/local/home/trivikr/workspace/aws-sdk-js-v3/clients/client-s3-control/dist/cjs/protocols/Aws_restXml.js:50:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /local/home/trivikr/workspace/aws-sdk-js-v3/packages/middleware-serde/dist/cjs/serializerMiddleware.js:11:21
(Use `node --trace-warnings ...` to show where the warning was created)
(node:27487) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:27487) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

</details>

**Comment by trivikr** [comment]
The code which throws error: https://github.com/aws/aws-sdk-js-v3/blob/043994681b2d1d90a628797c48e752d522a64f24/clients/client-s3-control/protocols/Aws_restXml.ts#L191-L193

**Comment by trivikr** [comment]
The code throwing error was updated in https://github.com/aws/aws-sdk-js-v3/pull/1553
